// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const MFA_REQUIRED = 'MFA_REQUIRED';
export const MFA_SUCCESS = 'MFA_SUCCESS';
export const MFA_FAIL = 'MFA_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// User Types
export const FETCH_USER_STATS_SUCCESS = 'FETCH_USER_STATS_SUCCESS';
export const FETCH_RECENT_ACTIVITY_SUCCESS = 'FETCH_RECENT_ACTIVITY_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const INVITE_USER_SUCCESS = 'INVITE_USER_SUCCESS';
export const INVITE_USER_FAIL = 'INVITE_USER_FAIL';

// Company Types
export const FETCH_COMPANY_SUCCESS = 'FETCH_COMPANY_SUCCESS';
export const FETCH_COMPANY_FAIL = 'FETCH_COMPANY_FAIL';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_FAIL = 'UPDATE_COMPANY_FAIL';
export const FETCH_COMPANY_STATS_SUCCESS = 'FETCH_COMPANY_STATS_SUCCESS';

// Property Types
export const FETCH_PROPERTIES_REQUEST = 'FETCH_PROPERTIES_REQUEST';
export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
export const FETCH_PROPERTIES_FAIL = 'FETCH_PROPERTIES_FAIL';
export const FETCH_PROPERTY_SUCCESS = 'FETCH_PROPERTY_SUCCESS';
export const FETCH_PROPERTY_FAIL = 'FETCH_PROPERTY_FAIL';
export const BOOKMARK_PROPERTY_SUCCESS = 'BOOKMARK_PROPERTY_SUCCESS';
export const BOOKMARK_PROPERTY_FAIL = 'BOOKMARK_PROPERTY_FAIL';
export const REMOVE_BOOKMARK_SUCCESS = 'REMOVE_BOOKMARK_SUCCESS';
export const FETCH_BOOKMARKS_SUCCESS = 'FETCH_BOOKMARKS_SUCCESS';

// Map Types
export const FETCH_MAP_PROPERTIES_REQUEST = 'FETCH_MAP_PROPERTIES_REQUEST';
export const FETCH_MAP_PROPERTIES_SUCCESS = 'FETCH_MAP_PROPERTIES_SUCCESS';
export const FETCH_MAP_PROPERTIES_FAIL = 'FETCH_MAP_PROPERTIES_FAIL';
export const SET_MAP_BOUNDS = 'SET_MAP_BOUNDS';
export const SET_MAP_CENTER = 'SET_MAP_CENTER';
export const SET_MAP_ZOOM = 'SET_MAP_ZOOM';
export const SET_MAP_FILTERS = 'SET_MAP_FILTERS';
export const SAVE_MAP_VIEW_SUCCESS = 'SAVE_MAP_VIEW_SUCCESS';
export const FETCH_SAVED_MAP_VIEWS_SUCCESS = 'FETCH_SAVED_MAP_VIEWS_SUCCESS';
export const DELETE_MAP_VIEW_SUCCESS = 'DELETE_MAP_VIEW_SUCCESS';
export const CLEAR_MAP_ERRORS = 'CLEAR_MAP_ERRORS';

// Wealth Types
export const FETCH_WEALTH_PROFILE_REQUEST = 'FETCH_WEALTH_PROFILE_REQUEST';
export const FETCH_WEALTH_PROFILE_SUCCESS = 'FETCH_WEALTH_PROFILE_SUCCESS';
export const FETCH_WEALTH_PROFILE_FAIL = 'FETCH_WEALTH_PROFILE_FAIL';
export const COMPARE_WEALTH_PROFILES_REQUEST = 'COMPARE_WEALTH_PROFILES_REQUEST';
export const COMPARE_WEALTH_PROFILES_SUCCESS = 'COMPARE_WEALTH_PROFILES_SUCCESS';
export const COMPARE_WEALTH_PROFILES_FAIL = 'COMPARE_WEALTH_PROFILES_FAIL';
export const FETCH_WEALTH_STATISTICS_SUCCESS = 'FETCH_WEALTH_STATISTICS_SUCCESS';
export const FETCH_PROPERTY_WEALTH_INSIGHTS_SUCCESS = 'FETCH_PROPERTY_WEALTH_INSIGHTS_SUCCESS';
export const CLEAR_WEALTH_ERRORS = 'CLEAR_WEALTH_ERRORS';

// Report Types
export const CREATE_REPORT_REQUEST = 'CREATE_REPORT_REQUEST';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAIL = 'CREATE_REPORT_FAIL';
export const FETCH_REPORTS_SUCCESS = 'FETCH_REPORTS_SUCCESS';
export const FETCH_REPORT_SUCCESS = 'FETCH_REPORT_SUCCESS';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const SCHEDULE_REPORT_SUCCESS = 'SCHEDULE_REPORT_SUCCESS';
export const CANCEL_SCHEDULE_SUCCESS = 'CANCEL_SCHEDULE_SUCCESS';
export const EXPORT_REPORT_SUCCESS = 'EXPORT_REPORT_SUCCESS';
export const FETCH_EXPORT_HISTORY_SUCCESS = 'FETCH_EXPORT_HISTORY_SUCCESS';
export const CLEAR_REPORT_ERRORS = 'CLEAR_REPORT_ERRORS';

// Search Types
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const SAVE_SEARCH_SUCCESS = 'SAVE_SEARCH_SUCCESS';
export const FETCH_SAVED_SEARCHES_SUCCESS = 'FETCH_SAVED_SEARCHES_SUCCESS';
export const DELETE_SAVED_SEARCH_SUCCESS = 'DELETE_SAVED_SEARCH_SUCCESS';
export const CLEAR_SEARCH_ERRORS = 'CLEAR_SEARCH_ERRORS';

// Alert Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';